### ISSUE TITLE
Support for Thundbird 60

### ISSUE THREAD

**Issue by ghost** [tinnyx/keepintaskbar#1]
It would be good were this extension to support Thunderbird 60. True, I can tell TB 60 to disable compatibility checking, and that does enable the extension to work, but that workaround will cause some people problems. It will cause some people problems because disabling the compatibility allows the operation of many extensions that break TB 60. I had to disable all the problematic extensions before TB 60, and your extension, would work.

**Comment by foguetes** [comment]
It still doesn't work in version 60.3.1

**Comment by martinzilak** [comment]
I've just submitted a new version for a review yesterday, it should be up and running in a few days. Sorry for the delay though.
