### ISSUE TITLE
Please update for TB v68

### ISSUE THREAD

**Issue by Taomyn** [tinnyx/keepintaskbar#3]
Great add-on but needs updating for Thunderbird v68 please if possible.

**Comment by MasterSoft24** [comment]
+1

**Comment by martinzilak** [comment]
I have just submitted an updated version, should be up in a few days.

**Comment by Taomyn** [comment]
Any idea when this will appear on the TB Add-Ons site? It's still not there.

**Comment by martinzilak** [comment]
> Any idea when this will appear on the TB Add-Ons site? It's still not there.

~~Really not sure, it's still in the "awaiting review" state, queue position 16/19. Nothing more I can do to speed it up I'm afraid.~~

The new version has just went live. I guess they prioritize the manual checking based on how many people visit the plugin's page, but who knows.

**Comment by Taomyn** [comment]
Confirmed, thank-you
